### PR TITLE
Circuit logic error

### PR DESCRIPTION
**Pull request by Unchain68**
Your original circuit can not make a proof with wrong witness.
But acutally it must make a proof whether the witness is wrong or not. 
So, that means this circuit needs an out signal.

### CODE REVIEW

**Comment by enricobottazzi** [comment]
Thanks for the PR. I agree with it. Could please check if the other scripts work as expected with this modification before merging? First thing that comes to my mind is that the verifier.sol contract has to be updated according to the modified circuit

**Comment by Unchain68** [comment]
Thanks for your comment. 
Actually, I made my own circuit for my dapp by using your circuit.  
So, that's why i found an error in zkp-circuit.
I'll check that the modified circuit works well. I also upload verifier.sol according to modified-circuit.

By the way, i found a mistake an document of iden3. 
So i made a pull request on iden3 doc. 
Could you please check it.

**Comment by Unchain68** [comment]
I changed circuit and new keys and wasm etc all the files according to modified-circuit. 
But, the change was succesfull.
I also changed verifier.sol
image

image

But, all of the files name and the location of them are the same as were. 
I do my best to follow what you did. 
But, I found the location of files are not friendly to read and test.
For that reason, how about changing the files' location.

I want to commit again after you commit the pull request i did before.
After you doing so, i can commit again. 
All of the pull requests i did will not make an error

**Comment by enricobottazzi** [comment]
Hi @Unchain68, I don't think that updating the file location would be beneficial as the readMe and the different scripts are built based on this directory structure. Would you be able to add the updated files inside the existing directory structure of the repo? 

Thanks

**Comment by Unchain68** [comment]
Hi @enricobottazzi 
I updated files to according to modified circuit. 
I understand what you are talking about.
I am also very interested in SSI. 
If you are available, I want to contact you.

Thanks

**Comment by enricobottazzi** [comment]
Hello @Unchain68, thanks for the updates. 
I just updated PrivateOver18Aidrop.sol contract to accomodate the new changes in the circuit. Does it make sense to you? 
Waiting from a feedback from you before testing it and, eventually, merging.

Of course you can contact me at enricobottazzi@icloud.com. Looking forward to it :)

Enrico

**Comment by Unchain68** [comment]
Enrico 

Yes, sure.
I have used your test code to test the modified circuit. 
There was no problem as the result that i upload.
However, there might be problem that i don't know. 
If that kind of situation happen, i will fix again.

Thanks

**Pull request merged**
